// Mock data for development
import { TelegramUser, Product, Order, Payment, SystemAlert, DashboardStats, Report, UserFeedback, SystemLog, Coupon, LicenseToken, ActivationLog } from './types'

export const mockUsers: TelegramUser[] = [
  {
    id: '1',
    telegramId: 123456789,
    username: 'user_alpha',
    firstName: 'Alex',
    lastName: 'Anderson',
    email: 'alex@example.com',
    status: 'active',
    totalOrders: 12,
    successfulOrders: 10,
    failedOrders: 2,
    totalSpending: 2400,
    registeredAt: new Date('2025-03-01'),
    lastActivityAt: new Date('2025-03-23'),
    internalNotes: 'Premium customer, consistent buyer',
  },
  {
    id: '2',
    telegramId: 987654321,
    username: 'user_beta',
    firstName: 'Bob',
    lastName: 'Brown',
    status: 'active',
    totalOrders: 5,
    successfulOrders: 4,
    failedOrders: 1,
    totalSpending: 900,
    registeredAt: new Date('2025-03-10'),
    lastActivityAt: new Date('2025-03-22'),
  },
  {
    id: '3',
    telegramId: 555666777,
    username: 'user_gamma',
    firstName: 'Carol',
    lastName: 'Chen',
    status: 'blocked',
    totalOrders: 0,
    successfulOrders: 0,
    failedOrders: 0,
    totalSpending: 0,
    registeredAt: new Date('2025-03-15'),
  },
]

export const mockProducts: Product[] = [
  {
    id: 'prod_1',
    name: 'Premium Access',
    slug: 'premium-access',
    description: 'Access to premium content and features',
    price: 99,
    currency: 'USD',
    durationDays: 30,
    activationType: 'auto',
    requiredFields: ['target_url'],
    isActive: true,
    salesCount: 342,
    totalRevenue: 33858,
    successRate: 96.5,
    failureRate: 3.5,
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-03-20'),
  },
  {
    id: 'prod_2',
    name: 'Enterprise Package',
    slug: 'enterprise-package',
    description: 'Full enterprise suite with support',
    price: 499,
    currency: 'USD',
    durationDays: 90,
    activationType: 'manual',
    requiredFields: ['target_url', 'company_name', 'contact_email'],
    isActive: true,
    salesCount: 45,
    totalRevenue: 22455,
    successRate: 98.0,
    failureRate: 2.0,
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2025-03-21'),
  },
  {
    id: 'prod_3',
    name: 'Starter Plan',
    slug: 'starter-plan',
    description: 'Perfect for getting started',
    price: 29,
    currency: 'USD',
    durationDays: 7,
    activationType: 'auto',
    requiredFields: ['target_url'],
    isActive: true,
    salesCount: 856,
    totalRevenue: 24824,
    successRate: 92.0,
    failureRate: 8.0,
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-03-22'),
  },
]

export const mockOrders: Order[] = [
  {
    id: 'ord_1001',
    userId: '1',
    productId: 'prod_1',
    targetUrl: 'https://example.com/target1',
    inputData: { service_type: 'api_access' },
    status: 'activated',
    paymentStatus: 'paid',
    activationStatus: 'success',
    amount: 99,
    currency: 'USD',
    retryCount: 0,
    createdAt: new Date('2025-03-23'),
    updatedAt: new Date('2025-03-23'),
    activatedAt: new Date('2025-03-23'),
  },
  {
    id: 'ord_1002',
    userId: '2',
    productId: 'prod_3',
    targetUrl: 'https://example.com/target2',
    inputData: {},
    status: 'processing',
    paymentStatus: 'paid',
    activationStatus: 'processing',
    amount: 29,
    currency: 'USD',
    retryCount: 1,
    createdAt: new Date('2025-03-23'),
    updatedAt: new Date('2025-03-23'),
  },
  {
    id: 'ord_1003',
    userId: '1',
    productId: 'prod_2',
    targetUrl: 'https://example.com/target3',
    inputData: { company: 'TechCorp' },
    status: 'manual_review',
    paymentStatus: 'paid',
    activationStatus: 'manual_review',
    amount: 499,
    currency: 'USD',
    adminNotes: 'Requires verification',
    retryCount: 2,
    createdAt: new Date('2025-03-22'),
    updatedAt: new Date('2025-03-23'),
  },
  {
    id: 'ord_1004',
    userId: '3',
    productId: 'prod_1',
    targetUrl: 'https://example.com/target4',
    inputData: {},
    status: 'failed',
    paymentStatus: 'paid',
    activationStatus: 'failed',
    amount: 99,
    currency: 'USD',
    adminNotes: 'Activation timeout',
    retryCount: 3,
    createdAt: new Date('2025-03-21'),
    updatedAt: new Date('2025-03-22'),
  },
]

export const mockPayments: Payment[] = [
  {
    id: 'pay_001',
    orderId: 'ord_1001',
    userId: '1',
    method: 'card',
    amount: 99,
    currency: 'USD',
    status: 'paid',
    transactionReference: 'txn_1234567890',
    paidAt: new Date('2025-03-23'),
    createdAt: new Date('2025-03-23'),
    updatedAt: new Date('2025-03-23'),
  },
  {
    id: 'pay_002',
    orderId: 'ord_1002',
    userId: '2',
    method: 'wallet',
    amount: 29,
    currency: 'USD',
    status: 'paid',
    transactionReference: 'txn_0987654321',
    paidAt: new Date('2025-03-23'),
    createdAt: new Date('2025-03-23'),
    updatedAt: new Date('2025-03-23'),
  },
  {
    id: 'pay_003',
    orderId: 'ord_1003',
    userId: '1',
    method: 'card',
    amount: 499,
    currency: 'USD',
    status: 'pending',
    transactionReference: 'txn_pending_123',
    createdAt: new Date('2025-03-22'),
    updatedAt: new Date('2025-03-22'),
  },
]


export const mockAlerts: SystemAlert[] = [
  {
    id: 'alert_1',
    type: 'warning',
    title: 'High Failed Activation Rate',
    message: 'Failed activation count increased to 8 in the last hour',
    createdAt: new Date('2025-03-23T14:00:00Z'),
  },
  {
    id: 'alert_2',
    type: 'warning',
    title: 'Payment Queue Backup',
    message: '12 payments pending verification',
    createdAt: new Date('2025-03-23T13:30:00Z'),
  },
  {
    id: 'alert_3',
    type: 'info',
    title: 'Daily Backup Complete',
    message: 'Database backup completed successfully',
    createdAt: new Date('2025-03-23T12:00:00Z'),
  },
]

export const mockReports: Report[] = [
  {
    id: 'rep_001',
    title: 'Daily Revenue Report',
    type: 'revenue',
    generatedAt: new Date('2025-03-23T09:00:00Z'),
    generatedBy: 'admin@dashboard.local',
    period: 'daily',
    startDate: new Date('2025-03-23'),
    endDate: new Date('2025-03-23'),
    metrics: {
      totalRevenue: 12450.50,
      totalOrders: 145,
      averageOrderValue: 85.86,
      topProduct: 'Premium Access',
      topProductRevenue: 5200,
    },
    description: 'Daily revenue summary for March 23, 2025',
  },
  {
    id: 'rep_002',
    title: 'Weekly Activation Report',
    type: 'activation',
    generatedAt: new Date('2025-03-23T08:30:00Z'),
    generatedBy: 'admin@dashboard.local',
    period: 'weekly',
    startDate: new Date('2025-03-17'),
    endDate: new Date('2025-03-23'),
    metrics: {
      totalActivations: 892,
      successfulActivations: 861,
      failedActivations: 31,
      successRate: 96.5,
      averageProcessingTime: '2.3 hours',
    },
    description: 'Weekly activation performance metrics',
  },
  {
    id: 'rep_003',
    title: 'Monthly Payment Report',
    type: 'payments',
    generatedAt: new Date('2025-03-22T23:59:00Z'),
    generatedBy: 'finance@dashboard.local',
    period: 'monthly',
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-03-23'),
    metrics: {
      totalPayments: 287300.00,
      paidPayments: 275200.00,
      pendingPayments: 12100.00,
      refundedPayments: 0,
      paymentMethods: { card: 65, wallet: 30, crypto: 5 },
    },
    description: 'Monthly payment processing and reconciliation report',
  },
  {
    id: 'rep_004',
    title: 'User Growth Report',
    type: 'users',
    generatedAt: new Date('2025-03-22T10:00:00Z'),
    generatedBy: 'admin@dashboard.local',
    period: 'weekly',
    startDate: new Date('2025-03-17'),
    endDate: new Date('2025-03-23'),
    metrics: {
      totalUsers: 1243,
      newUsersThisWeek: 87,
      activeUsers: 1098,
      blockedUsers: 45,
      churnRate: 2.1,
    },
    description: 'Weekly user growth and engagement metrics',
  },
]

export const mockFeedback: UserFeedback[] = [
  {
    id: 'fb_001',
    userId: '1',
    email: 'alex@example.com',
    feedbackType: 'bug',
    subject: 'Order activation fails intermittently',
    message: 'Sometimes my orders fail to activate after payment. Happens about 20% of the time. Retrying helps but is frustrating.',
    priority: 'high',
    status: 'in_progress',
    createdAt: new Date('2025-03-22T14:30:00Z'),
    updatedAt: new Date('2025-03-23T08:00:00Z'),
    internalNotes: 'Investigating timeout issues in activation queue. Appears related to high load periods.',
  },
  {
    id: 'fb_002',
    email: 'user@example.com',
    feedbackType: 'feature',
    subject: 'Request: Bulk order creation',
    message: 'Would love ability to create multiple orders at once. Currently I need to submit each individually which is tedious.',
    priority: 'medium',
    status: 'new',
    createdAt: new Date('2025-03-23T10:15:00Z'),
    updatedAt: new Date('2025-03-23T10:15:00Z'),
  },
  {
    id: 'fb_003',
    email: 'support@company.com',
    feedbackType: 'general',
    subject: 'Dashboard is great but could use dark mode',
    message: 'Love the modern interface. A dark mode toggle would be really helpful for night usage.',
    priority: 'low',
    status: 'new',
    createdAt: new Date('2025-03-23T11:45:00Z'),
    updatedAt: new Date('2025-03-23T11:45:00Z'),
  },
  {
    id: 'fb_004',
    email: 'admin@example.com',
    feedbackType: 'performance',
    subject: 'Orders list takes time to load',
    message: 'When there are many orders with filters applied, the page takes 5+ seconds to load. Should optimize queries.',
    priority: 'high',
    status: 'resolved',
    createdAt: new Date('2025-03-21T09:00:00Z'),
    updatedAt: new Date('2025-03-23T15:30:00Z'),
    resolvedAt: new Date('2025-03-23T15:30:00Z'),
    resolvedBy: 'admin@dashboard.local',
    internalNotes: 'Added database indexes and pagination. Performance improved by 60%.',
  },
]

export const mockLogs: SystemLog[] = [
  {
    id: 'log_001',
    actor: 'admin@dashboard.local',
    action: 'UPDATE_ORDER_STATUS',
    targetType: 'order',
    targetId: 'ord_1001',
    metadata: { previousStatus: 'processing', newStatus: 'activated', reason: 'manual_activation' },
    ipAddress: '192.168.1.100',
    status: 'success',
    timestamp: new Date('2025-03-23T14:30:00Z'),
  },
  {
    id: 'log_003',
    actor: 'finance@dashboard.local',
    action: 'CONFIRM_PAYMENT',
    targetType: 'payment',
    targetId: 'pay_003',
    metadata: { amount: 499, method: 'card', transactionRef: 'txn_pending_123' },
    ipAddress: '192.168.1.110',
    status: 'success',
    timestamp: new Date('2025-03-23T12:15:00Z'),
  },
  {
    id: 'log_004',
    actor: 'super_admin@dashboard.local',
    action: 'BLOCK_USER',
    targetType: 'user',
    targetId: '3',
    metadata: { username: 'user_gamma', reason: 'suspicious_activity' },
    ipAddress: '192.168.1.120',
    status: 'success',
    timestamp: new Date('2025-03-23T11:00:00Z'),
  },
  {
    id: 'log_005',
    actor: 'support@dashboard.local',
    action: 'ADD_INTERNAL_NOTE',
    targetType: 'order',
    targetId: 'ord_1003',
    metadata: { note: 'Customer verified - ready for manual activation', previousNote: 'Requires verification' },
    ipAddress: '192.168.1.108',
    status: 'success',
    timestamp: new Date('2025-03-23T09:30:00Z'),
  },
]

export const mockDashboardStats: DashboardStats = {
  totalUsers: 1243,
  totalActiveProducts: 3,
  totalOrders: 2845,
  pendingOrders: 156,
  processingOrders: 43,
  activatedOrders: 2512,
  failedOrders: 89,
  manualReviewOrders: 45,
  todayRevenue: 12450.50,
  monthRevenue: 287300.00,
  failedActivationCount: 8,
  paymentPendingCount: 12,
  recentAlerts: mockAlerts,
}

export const mockCoupons: Coupon[] = [
  {
    id: 'coup_001',
    code: 'SAVE20',
    type: 'percentage',
    value: 20,
    description: '20% off all products',
    maxUsage: 500,
    currentUsage: 287,
    associatedProducts: ['prod_1', 'prod_2', 'prod_3'],
    minOrderValue: 50,
    expiryDate: new Date('2025-06-30'),
    status: 'active',
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date('2025-03-20'),
    createdBy: 'admin@dashboard.local',
  },
  {
    id: 'coup_002',
    code: 'FLAT10',
    type: 'fixed',
    value: 10,
    description: '$10 off on premium products',
    maxUsage: 200,
    currentUsage: 156,
    associatedProducts: ['prod_1', 'prod_2'],
    minOrderValue: 99,
    maxDiscount: 10,
    expiryDate: new Date('2025-05-15'),
    status: 'active',
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-03-22'),
    createdBy: 'admin@dashboard.local',
  },
  {
    id: 'coup_003',
    code: 'WELCOME15',
    type: 'percentage',
    value: 15,
    description: 'Welcome discount for new users',
    maxUsage: 1000,
    currentUsage: 234,
    associatedProducts: ['prod_3'],
    expiryDate: new Date('2025-12-31'),
    status: 'active',
    createdAt: new Date('2025-03-10'),
    updatedAt: new Date('2025-03-21'),
    createdBy: 'admin@dashboard.local',
  },
  {
    id: 'coup_004',
    code: 'SUMMER30',
    type: 'percentage',
    value: 30,
    description: 'Summer special - 30% off',
    maxUsage: 300,
    currentUsage: 298,
    associatedProducts: ['prod_1', 'prod_2', 'prod_3'],
    minOrderValue: 100,
    expiryDate: new Date('2025-04-30'),
    status: 'inactive',
    createdAt: new Date('2025-02-20'),
    updatedAt: new Date('2025-03-15'),
    createdBy: 'admin@dashboard.local',
  },
  {
    id: 'coup_005',
    code: 'EXPIRED50',
    type: 'percentage',
    value: 50,
    description: 'Black Friday deal (expired)',
    maxUsage: 500,
    currentUsage: 487,
    associatedProducts: ['prod_1', 'prod_2', 'prod_3'],
    expiryDate: new Date('2025-02-28'),
    status: 'expired',
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2025-02-28'),
    createdBy: 'admin@dashboard.local',
  },
]

export const mockLicenseTokens: LicenseToken[] = [
  {
    id: 'lt_001',
    tokenCode: 'PREM-A1B2-C3D4-E5F6',
    userId: '1',
    productId: 'prod_1',
    orderId: 'ord_1001',
    status: 'activated',
    createdAt: new Date('2025-03-23T08:00:00Z'),
    activatedAt: new Date('2025-03-23T10:30:00Z'),
    boundDevice: 'MacBook Pro 16" (M3)',
    boundAccount: 'alex@example.com',
    verifyAttemptCount: 3,
    lastVerifyAttempt: new Date('2025-03-23T14:00:00Z'),
  },
  {
    id: 'lt_002',
    tokenCode: 'STRT-G7H8-I9J0-K1L2',
    userId: '2',
    productId: 'prod_3',
    orderId: 'ord_1002',
    status: 'paid_not_activated',
    createdAt: new Date('2025-03-23T09:15:00Z'),
    verifyAttemptCount: 1,
    lastVerifyAttempt: new Date('2025-03-23T09:20:00Z'),
  },
  {
    id: 'lt_003',
    tokenCode: 'ENTR-M3N4-O5P6-Q7R8',
    userId: '1',
    productId: 'prod_2',
    orderId: 'ord_1003',
    status: 'paid_not_activated',
    createdAt: new Date('2025-03-22T14:00:00Z'),
    verifyAttemptCount: 2,
    lastVerifyAttempt: new Date('2025-03-23T11:00:00Z'),
  },
  {
    id: 'lt_004',
    tokenCode: 'PREM-S9T0-U1V2-W3X4',
    userId: '3',
    productId: 'prod_1',
    orderId: 'ord_1004',
    status: 'revoked',
    createdAt: new Date('2025-03-21T10:00:00Z'),
    activatedAt: new Date('2025-03-21T12:00:00Z'),
    boundDevice: 'Windows Desktop (Unknown)',
    verifyAttemptCount: 15,
    lastVerifyAttempt: new Date('2025-03-22T23:59:00Z'),
  },
  {
    id: 'lt_005',
    tokenCode: 'STRT-Y5Z6-A7B8-C9D0',
    userId: '2',
    productId: 'prod_3',
    orderId: 'ord_1002',
    status: 'activated',
    createdAt: new Date('2025-03-20T16:30:00Z'),
    activatedAt: new Date('2025-03-20T17:00:00Z'),
    boundDevice: 'iPhone 15 Pro',
    boundAccount: 'bob.brown@email.com',
    verifyAttemptCount: 1,
    lastVerifyAttempt: new Date('2025-03-20T17:00:00Z'),
  },
  {
    id: 'lt_006',
    tokenCode: 'PREM-E1F2-G3H4-I5J6',
    userId: '1',
    productId: 'prod_1',
    orderId: 'ord_1001',
    status: 'activated',
    createdAt: new Date('2025-03-19T11:00:00Z'),
    activatedAt: new Date('2025-03-19T11:15:00Z'),
    boundDevice: 'iPad Air (5th gen)',
    boundAccount: 'alex@example.com',
    verifyAttemptCount: 2,
    lastVerifyAttempt: new Date('2025-03-21T09:00:00Z'),
  },
  {
    id: 'lt_007',
    tokenCode: 'ENTR-K7L8-M9N0-O1P2',
    userId: '1',
    productId: 'prod_2',
    orderId: 'ord_1003',
    status: 'paid_not_activated',
    createdAt: new Date('2025-03-23T15:00:00Z'),
    verifyAttemptCount: 0,
  },
]

export const mockActivationLogs: ActivationLog[] = [
  {
    id: 'alog_001',
    tokenId: 'lt_001',
    tokenCode: 'PREM-A1B2-C3D4-E5F6',
    userId: '1',
    productId: 'prod_1',
    result: 'success',
    ipAddress: '103.45.67.89',
    deviceInfo: 'Chrome 121 / macOS 14.3',
    attemptTime: new Date('2025-03-23T10:30:00Z'),
    location: 'Jakarta, ID',
    requestSource: 'web_app',
    appVersion: 'v2.4.1',
  },
  {
    id: 'alog_002',
    tokenId: 'lt_002',
    tokenCode: 'STRT-G7H8-I9J0-K1L2',
    userId: '2',
    productId: 'prod_3',
    result: 'failed',
    failureReason: 'Token not yet paid — payment still processing',
    ipAddress: '202.134.0.55',
    deviceInfo: 'Firefox 122 / Windows 11',
    attemptTime: new Date('2025-03-23T09:20:00Z'),
    location: 'Surabaya, ID',
    requestSource: 'desktop_app',
    appVersion: 'v2.4.0',
  },
  {
    id: 'alog_003',
    tokenId: 'lt_004',
    tokenCode: 'PREM-S9T0-U1V2-W3X4',
    userId: '3',
    productId: 'prod_1',
    result: 'failed',
    failureReason: 'Token has been revoked due to abuse',
    ipAddress: '185.220.100.240',
    deviceInfo: 'Unknown / TOR Browser',
    attemptTime: new Date('2025-03-22T23:59:00Z'),
    location: 'Unknown (TOR)',
    requestSource: 'api',
    appVersion: 'v2.3.8',
  },
  {
    id: 'alog_004',
    tokenId: 'lt_001',
    tokenCode: 'PREM-A1B2-C3D4-E5F6',
    userId: '1',
    productId: 'prod_1',
    result: 'success',
    ipAddress: '103.45.67.89',
    deviceInfo: 'Chrome 121 / macOS 14.3',
    attemptTime: new Date('2025-03-23T14:00:00Z'),
    location: 'Jakarta, ID',
    requestSource: 'web_app',
    appVersion: 'v2.4.1',
  },
  {
    id: 'alog_005',
    tokenId: 'lt_003',
    tokenCode: 'ENTR-M3N4-O5P6-Q7R8',
    userId: '1',
    productId: 'prod_2',
    result: 'failed',
    failureReason: 'Device limit exceeded — max 1 device allowed',
    ipAddress: '103.45.67.90',
    deviceInfo: 'Safari 17 / iOS 17.3',
    attemptTime: new Date('2025-03-23T11:00:00Z'),
    location: 'Jakarta, ID',
    requestSource: 'mobile_app',
    appVersion: 'v1.8.2',
  },
  {
    id: 'alog_006',
    tokenId: 'lt_005',
    tokenCode: 'STRT-Y5Z6-A7B8-C9D0',
    userId: '2',
    productId: 'prod_3',
    result: 'success',
    ipAddress: '202.134.0.55',
    deviceInfo: 'Safari 17 / iOS 17.3',
    attemptTime: new Date('2025-03-20T17:00:00Z'),
    location: 'Surabaya, ID',
    requestSource: 'mobile_app',
    appVersion: 'v1.8.0',
  },
  {
    id: 'alog_007',
    tokenId: 'lt_004',
    tokenCode: 'PREM-S9T0-U1V2-W3X4',
    userId: '3',
    productId: 'prod_1',
    result: 'failed',
    failureReason: 'IP address blacklisted',
    ipAddress: '185.220.100.240',
    deviceInfo: 'Unknown / TOR Browser',
    attemptTime: new Date('2025-03-22T22:30:00Z'),
    location: 'Unknown (TOR)',
    requestSource: 'api',
    appVersion: 'v2.3.8',
  },
  {
    id: 'alog_008',
    tokenId: 'lt_006',
    tokenCode: 'PREM-E1F2-G3H4-I5J6',
    userId: '1',
    productId: 'prod_1',
    result: 'success',
    ipAddress: '103.45.67.91',
    deviceInfo: 'Safari 17 / iPadOS 17.3',
    attemptTime: new Date('2025-03-19T11:15:00Z'),
    location: 'Jakarta, ID',
    requestSource: 'web_app',
    appVersion: 'v2.4.0',
  },
  {
    id: 'alog_009',
    tokenId: 'lt_004',
    tokenCode: 'PREM-S9T0-U1V2-W3X4',
    userId: '3',
    productId: 'prod_1',
    result: 'success',
    ipAddress: '110.76.148.22',
    deviceInfo: 'Chrome 120 / Windows 11',
    attemptTime: new Date('2025-03-21T12:00:00Z'),
    location: 'Bandung, ID',
    requestSource: 'desktop_app',
    appVersion: 'v2.3.5',
  },
  {
    id: 'alog_010',
    tokenId: 'lt_003',
    tokenCode: 'ENTR-M3N4-O5P6-Q7R8',
    userId: '1',
    productId: 'prod_2',
    result: 'failed',
    failureReason: 'Token not activated — awaiting manual review',
    ipAddress: '103.45.67.89',
    deviceInfo: 'Chrome 121 / macOS 14.3',
    attemptTime: new Date('2025-03-22T16:00:00Z'),
    location: 'Jakarta, ID',
    requestSource: 'web_app',
    appVersion: 'v2.4.1',
  },
]
